dataset_root: /root/dataset/Market
workers: 8
height: 256
width: 128
arch: ResNet50

loss: softmax,metric #or metric or softmax,metric
train_epoch: 300 #60
train_batch: 32
test_batch:  32
lr: 0.0003
step_size: 20
gamma: 0.85
weight_decay: 0.0005

#about triplet
margin: 0.15
num_instances: 4
